sudo: false
language: rust

cache:
  - cargo

install:
  - "script/bootstrap"

script:
  - "script/cibuild"

after_script:
  - "script/after_cibuild"

rust:
  - nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - texinfo
      - graphviz
      - libdbus-1-dev
      - libdbus-1-3`

notifications:
  email:
    on_success: never
    on_failure: always
  irc:
    channels:
      - "ircs://irc.mozilla.org:6697/#scrobble.rs"
    nick: scrobbers-ci
    on_success: never
    on_failure: always
    use_notice: true
    skip_join: false
