[workspace]
members = [
    "lib/db",
    "lib/rpc",
    "lib/sources",
    "lib/targets",
    "lib/dyn",
    "bin/controllers/cli",
    "bin/daemon"
]

[profile.release]
lto = "on"
opt-level = 'z'
codegen-units = 1
