
[package]
name = "scrobblers-controllers-cli"
version = "0.1.0"
authors = ["Dom Rodriguez <shymega@shymega.org.uk"]
edition = "2018"

[dependencies]
slog = "2.5.2"
slog-async = "2.3.0"
slog-scope = "4.1.2"
slog-term = "2.4.1"
serde = "1.0.98"
serde_json = "1.0.40"

[dependencies.clap]
features = ["suggestions", "color", "wrap_help"]
version = "2.33.0"

[dependencies.clippy]
version = "0.0.302"
optional = true
