name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu19.04

    steps:
    - uses: actions/checkout@v1
    - name: Update aptitude
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install -y libdbus1-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
